# -*- coding: utf-8 -*-
"""cleanlaptopdata.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JmXqwRK3-qFnwXIfgYhcJP0wygqGlw3f

# UPLOAD FILE XLSX
"""

from google.colab import files
uploaded = files.upload()

"""# READ FILE"""

import pandas as pd
my_dic = pd.read_excel('raw-data-laptops.xlsx', index_col=0).to_dict()

dataset = pd.DataFrame(data = my_dic)

dataset['ram'] = dataset['RAM'].copy() # Creating a copy of RAM
dataset['ram'].unique()

print(dataset['ram'])

"""# RAM"""

ram_in_gb = []
for i in dataset['ram']:
  if('64' in i):
    ram_in_gb.append('64')
  elif('32' in i): # 32GB RAM
    ram_in_gb.append('32')
  elif('16' in i): # 16GB RAM
    ram_in_gb.append('16')
  elif('8' in i): # 8GB RAM
    ram_in_gb.append('8')
  elif('6' in i): # 6GB RAM
    ram_in_gb.append('6')
  elif('4' in i): # 4GB RAM
    ram_in_gb.append('4')
dataset['ram_in_gb'] = ram_in_gb
print(len(ram_in_gb))
dataset['ram_in_gb']

"""# PROCESSOR"""

dataset['processor'] = dataset['Processor'].copy() # Creating a copy of Processor
dataset['processor'] = dataset['processor'].apply(lambda x:x.replace("\n", "").replace("\t", ""))
gen = dataset['processor'].apply(lambda x:x.replace("Intel Core", ""))
dataset['processor'].unique()

dataset['processor']

gen

"""# Processor Type

"""

processor_type = []
for i in (gen):
    processor_type.append(" ".join(i.split()))
processor_type
dataset['processor_type'] = processor_type
print(len(processor_type))
dataset['processor_type']

"""# Processor name"""

processor_name = []
for i in dataset['processor']:
  if('Intel' in i): 
    processor_name.append('Intel')
  elif('AMD' in i):
    processor_name.append('AMD')
  elif('Microsoft' in i):
    processor_name.append('Microsoft')
  elif('Apple' in i):
    processor_name.append('Microsoft')
  else:
    processor_name.append('Intel')
dataset['processor_name'] = processor_name
print(len(processor_name))
dataset['processor_name']

"""# Storage"""

dataset['storage'] = dataset['Storage'].copy() # Creating a copy of Storage
dataset['storage'].unique()

dataset['storage']

disk_drive = []
for y in dataset['storage']:
    if('HDD' in str(y) and 'SSD' not in str(y)):   # If only HDD
      disk_drive.append('HDD')
    elif('SSD' in str(y) and 'HDD' not in str(y)): # If only SSD
      disk_drive.append('SSD')
    elif('+' in str(y)):     # If both HDD and SSD
      disk_drive.append("Both")
    else:
      disk_drive.append("SSD")
dataset['disk_drive'] = disk_drive
print(len(disk_drive))
dataset['disk_drive']

storage_in_SSD = []
for i in dataset['storage']:
  if '+' not in str(i):
    if 'SSD' not in str(i):
      storage_in_SSD.append("0")
    elif 'SSD' in str(i):
      if('512' in str(i) and 'TB' not in str(i) and 'HDD' not in str(i)): # Only 512GB SSD
        storage_in_SSD.append('512')
      elif('256' in str(i) and 'TB' not in str(i) and 'HDD' not in str(i)): # Only 256GB SSD
        storage_in_SSD.append('256')
      elif('128' in str(i) and 'TB' not in str(i) and 'HDD' not in str(i)): # Only 128GB SSD
        storage_in_SSD.append('128')
      elif('64' in str(i) and 'TB' not in str(i) and 'HDD' not in str(i)): # Only 64GB SSD
        storage_in_SSD.append('64')
      elif('1' in str(i) and '256' not in str(i) and '512' not in str(i) and 'HDD' not in str(i)): # Only 1TB SSD
        storage_in_SSD.append('1000')
      elif('2' in str(i) and '256' not in str(i) and '512' not in str(i) and 'HDD' not in str(i)): # Only 2TB SSD
        storage_in_SSD.append('2000')
  elif '+' in str(i):
    x = str(i).split("+")
    for y in x:
      if('SSD' in str(y)):
        if('512' in str(y) and 'TB' not in str(y)): # Only 512GB SSD
          storage_in_SSD.append('512')
        elif('256' in str(y) and 'TB' not in str(y)): # Only 256GB SSD
          storage_in_SSD.append('256')
        elif('128' in str(y) and 'TB' not in str(y)): # Only 128GB SSD
          storage_in_SSD.append('128')
        elif('1' in str(y) and '256' not in str(y) and '512' not in str(y)): # Only 1TB SSD
          storage_in_SSD.append('1000')
        elif('2' in str(y) and '256' not in str(y) and '512' not in str(y)): # Only 2TB SSD
          storage_in_SSD.append('2000')
dataset['storage_in_SSD'] = storage_in_SSD
print(len(storage_in_SSD))
dataset['storage_in_SSD']

storage_in_HDD = []
for i in dataset['storage']:
  if '+' not in str(i):
    if 'HDD' not in str(i):
      storage_in_HDD.append("0")
    elif 'HDD' in str(i):
      if('512' in str(i) and 'TB' not in str(i) and 'SSD' not in str(i)): # Only 512GB HDD
        storage_in_HDD.append('512')
      elif('256' in str(i) and 'TB' not in str(i) and 'SSD' not in str(i)): # Only 256GB HDD
        storage_in_HDD.append('256')
      elif('128' in str(i) and 'TB' not in str(i) and 'SSD' not in str(i)): # Only 128GB HDD
        storage_in_HDD.append('128')
      elif('64' in str(i) and 'TB' not in str(i) and 'SSD' not in str(i)): # Only 64GB HDD
        storage_in_HDD.append('64')
      elif('1' in str(i) and '256' not in str(i) and '512' not in str(i) and 'SSD' not in str(i)): # Only 1TB HDD
        storage_in_HDD.append('1000')
      elif('2' in str(i) and '256' not in str(i) and '512' not in str(i) and 'SSD' not in str(i)): # Only 2TB HDD
        storage_in_HDD.append('2000')
  elif '+' in i:
    x = i.split("+")
    for y in x:
      if('HDD' in str(y)):
        if('512' in str(y) and 'TB' not in str(y)): # Only 512GB HDD
          storage_in_HDD.append('512')
        elif('256' in str(y) and 'TB' not in str(y)): # Only 256GB HDD
          storage_in_HDD.append('256')
        elif('128' in str(y) and 'TB' not in str(y)): # Only 128GB SSD or 128GB HDD
          storage_in_HDD.append('128')
        elif('1' in str(y) and '256' not in str(y) and '512' not in str(y)): # Only 1TB HDD
          storage_in_HDD.append('1000')
        elif('2' in str(y) and '256' not in str(y) and '512' not in str(y)): # Only 2TB HDD
          storage_in_HDD.append('2000')
dataset['storage_in_HDD'] = storage_in_HDD
print(len(storage_in_HDD))
dataset['storage_in_HDD']

"""# Display"""

dataset['display'] = dataset['Display'].copy() # Creating a copy of Display
dataset['display'].unique()

dataset['display']

size_in_inches = []
for i in dataset['display']:
  if('18.4' in str(i)):  
    size_in_inches.append('18.4')
  elif('17.3' in str(i)): 
    size_in_inches.append('17.3')
  elif('17' in str(i) or '17.0' in str(i)): 
    size_in_inches.append('17')
  elif('16' in str(i) or '16.0'):   
    size_in_inches.append('16')
  elif('15.6' in str(i)):   
    size_in_inches.append('15.6')
  elif('15' in str(i) or '15.0' in str(i)):    
    size_in_inches.append('15')
  elif('14.5' in str(i)):  
    size_in_inches.append('14.5')
  elif('14' in str(i) or '14.0' in str(i)):  
    size_in_inches.append('14')
  elif('13.7' in str(i)):    
    size_in_inches.append('13.7')
  elif('13.5' in str(i)): 
    size_in_inches.append('13.5')
  elif('13.4' in str(i)):    
    size_in_inches.append('13.4')
  elif('13.3' in str(i)):  
    size_in_inches.append('13.3')
  elif('13' in str(i) or '13.0' in str(i)):    
    size_in_inches.append('13')
  elif('12.5' in str(i)):   
    size_in_inches.append('12.5')
  elif('12.4' in str(i)):   
    size_in_inches.append('12.4')
  elif('12.3' in str(i)):   
    size_in_inches.append('12.3')
  elif('11' in str(i) or '11.0' in str(i) or '11.6' in str(i)):  
    size_in_inches.append('11.6')
  elif('10' in str(i) or '10.0' in str(i) or '10.5' in str(i)):  
    size_in_inches.append('10.5')
dataset['size_in_inches'] = size_in_inches
print(len(size_in_inches))
dataset['size_in_inches']

"""# Decriptions"""

dataset['description'] = dataset['Description'].copy() # Creating a copy of Description
dataset['description'].unique # All the laptops are unique
# dataset['description']

company = []
for i in dataset['description']:
  if('Dell' in i or 'DELL'):           
    company.append('Dell')
  elif('Asus' in i or 'ASUS' in i):         
    company.append('Asus')
  elif('Lenovo' in i or 'LENOVO'):        
    company.append('Lenovo')
  elif('Acer' in i or 'ACER'):         
    company.append('Acer')
  elif('HP' in i):           
    company.append('HP')
  elif('LG' in i): 
    company.append('LG')
  elif('MSI' in i):          
    company.append('MSI')
  elif('Avita' in i or 'AVITA' in i): 
    company.append('Avita')
  elif('Microsoft' in i or 'Surface' or 'MICROSOFT'): 
    company.append('Microsoft')
  elif('Apple' in i):        
    company.append('Apple')
dataset['company'] = company
print(len(company))
dataset['company']

"""# Graphic Cards"""

dataset['card'] = dataset['Card'].copy() # Creating a copy of Description
card = dataset['card'].apply(lambda x:x.replace("NVIDIA ", "").replace("AMD ", "").replace("Intel ", "").replace("Nvidia ", "").replace("Radeon ", "").replace("INvidia ", ""))
dataset['card'].unique # All the laptops are unique
# dataset['description']

card

graphic_card_company = []
for i in dataset['card']:
  if('Onboard' in i):
    graphic_card_company.append('Onboard')
  elif ('INVIDIA' in i or 'NVIDIA' in i):
    graphic_card_company.append("NVIDIA")
  elif ('AMD' in i):
    graphic_card_company.append("AMD")
  elif ('Intel' in i):
    graphic_card_company.append("Intel")
  elif ('Intel' in i):
    graphic_card_company.append("Intel")
  elif ('Radeon' in i):
    graphic_card_company.append("Radeon")
  elif ('Radeon' not in i and 'Intel' not in i and 'AMD' not in i and 'INVIDIA' not in i and 'NVIDIA' not in i and 'Onboard' not in i):
    graphic_card_company.append("Intel")
dataset['graphic_card_company'] = graphic_card_company
print(len(graphic_card_company))
dataset['graphic_card_company']

graphic_card = []
for i in card:
  graphic_card.append(i)
dataset['graphic_card'] = graphic_card
print(len(graphic_card))
dataset['graphic_card']

dataset

dataset.drop(['ram','storage','processor','card','display', 'Description', 'Processor', 'Card', 'RAM', 'Display'],axis=1,inplace=True)

dataset

dataset.to_excel('datalaptop-cleaned.xlsx')